# Generated by Django 2.2.3 on 2020-01-08 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import schoolDarshika.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=schoolDarshika.helpers.PathAndRenameFile('amenities'))),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(default='Warangal', max_length=100)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('lat', models.FloatField(default=17.9689)),
                ('lng', models.FloatField(default=79.5941)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=schoolDarshika.helpers.PathAndRenameFile('amenities'))),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=schoolDarshika.helpers.PathAndRenameFile('amenities'))),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAmenityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=5)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Amenity')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('resource_uri', models.CharField(max_length=300)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAmenityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Amenity')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Feedback')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.School'),
        ),
    ]
