# Generated by Django 2.2.3 on 2020-01-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200108_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ngo',
            field=models.BooleanField(default=False),
        ),
    ]
