# Generated by Django 2.2.3 on 2020-01-11 07:28

from django.db import migrations, models
import django.db.models.deletion
import schoolDarshika.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_is_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to=schoolDarshika.helpers.PathAndRenameFile('uploads'))),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbackamenityscore',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='main.Feedback'),
        ),
        migrations.AlterField(
            model_name='schoolamenityscore',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='main.School'),
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Feedback')),
                ('image_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ImageUpload')),
            ],
        ),
    ]
